-- novilloencaos / resonancias + notas
-- Ejecutar una vez en Supabase SQL Editor.
-- El frontend usa exclusivamente claves públicas; nunca usar service_role en GitHub Pages.

begin;

create table if not exists public.nvc_resonances (
  id bigint generated by default as identity primary key,
  record text not null check (record ~ '^REC://[A-Z0-9-]+$'),
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (record, user_id)
);

create index if not exists nvc_resonances_record_idx
  on public.nvc_resonances (record);

create index if not exists nvc_resonances_user_idx
  on public.nvc_resonances (user_id);

create table if not exists public.nvc_notes (
  id bigint generated by default as identity primary key,
  record text not null check (record ~ '^REC://[A-Z0-9-]+$'),
  user_id uuid not null references auth.users(id) on delete cascade,
  alias text,
  body text not null,
  status text not null default 'published'
    check (status in ('published', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  check (char_length(body) between 3 and 1200),
  check (alias is null or char_length(alias) <= 40)
);

create index if not exists nvc_notes_record_status_created_idx
  on public.nvc_notes (record, status, created_at);

create index if not exists nvc_notes_user_created_idx
  on public.nvc_notes (user_id, created_at desc);

create table if not exists public.nvc_blocked_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.nvc_resonances enable row level security;
alter table public.nvc_notes enable row level security;
alter table public.nvc_blocked_users enable row level security;

-- No se otorga acceso directo a tablas desde el cliente.
revoke all on table public.nvc_resonances from anon, authenticated;
revoke all on table public.nvc_notes from anon, authenticated;
revoke all on table public.nvc_blocked_users from anon, authenticated;

create or replace function public.nvc_get_interaction_counts(p_records text[])
returns table (
  record text,
  resonance_count bigint,
  note_count bigint,
  viewer_resonated boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if coalesce(array_length(p_records, 1), 0) > 50 then
    raise exception 'too_many_records';
  end if;

  return query
  with requested as (
    select distinct upper(trim(value)) as rec
    from unnest(coalesce(p_records, array[]::text[])) as u(value)
    where upper(trim(value)) ~ '^REC://[A-Z0-9-]+$'
  )
  select
    requested.rec,
    (select count(*) from public.nvc_resonances r where r.record = requested.rec),
    (select count(*) from public.nvc_notes n where n.record = requested.rec and n.status = 'published'),
    case
      when auth.uid() is null then false
      else exists (
        select 1
        from public.nvc_resonances vr
        where vr.record = requested.rec
          and vr.user_id = auth.uid()
      )
    end
  from requested;
end;
$$;

create or replace function public.nvc_list_notes(p_record text)
returns table (
  id bigint,
  alias text,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_record text := upper(trim(coalesce(p_record, '')));
begin
  if v_record !~ '^REC://[A-Z0-9-]+$' then
    raise exception 'invalid_record';
  end if;

  return query
  select n.id, n.alias, n.body, n.created_at
  from public.nvc_notes n
  where n.record = v_record
    and n.status = 'published'
  order by n.created_at asc
  limit 100;
end;
$$;

create or replace function public.nvc_toggle_resonance(p_record text)
returns table (
  record text,
  resonance_count bigint,
  viewer_resonated boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_record text := upper(trim(coalesce(p_record, '')));
  v_active boolean;
  v_count bigint;
begin
  if v_user is null then
    raise exception 'authentication_required';
  end if;

  if v_record !~ '^REC://[A-Z0-9-]+$' then
    raise exception 'invalid_record';
  end if;

  if exists (select 1 from public.nvc_blocked_users b where b.user_id = v_user) then
    raise exception 'blocked_user';
  end if;

  if exists (
    select 1
    from public.nvc_resonances r
    where r.record = v_record and r.user_id = v_user
  ) then
    delete from public.nvc_resonances r
    where r.record = v_record and r.user_id = v_user;
    v_active := false;
  else
    insert into public.nvc_resonances (record, user_id)
    values (v_record, v_user)
    on conflict (record, user_id) do nothing;
    v_active := true;
  end if;

  select count(*) into v_count
  from public.nvc_resonances r
  where r.record = v_record;

  return query select v_record, v_count, v_active;
end;
$$;

create or replace function public.nvc_add_note(
  p_record text,
  p_alias text,
  p_body text,
  p_website text default ''
)
returns table (
  note_id bigint,
  note_count bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user uuid := auth.uid();
  v_record text := upper(trim(coalesce(p_record, '')));
  v_alias text := nullif(trim(coalesce(p_alias, '')), '');
  v_body text := trim(coalesce(p_body, ''));
  v_note_id bigint;
  v_count bigint;
begin
  if v_user is null then
    raise exception 'authentication_required';
  end if;

  if coalesce(trim(p_website), '') <> '' then
    raise exception 'invalid_request';
  end if;

  if v_record !~ '^REC://[A-Z0-9-]+$' then
    raise exception 'invalid_record';
  end if;

  if char_length(v_body) < 3 or char_length(v_body) > 1200 then
    raise exception 'invalid_note';
  end if;

  if v_alias is not null and char_length(v_alias) > 40 then
    raise exception 'invalid_alias';
  end if;

  if exists (select 1 from public.nvc_blocked_users b where b.user_id = v_user) then
    raise exception 'blocked_user';
  end if;

  if exists (
    select 1
    from public.nvc_notes n
    where n.user_id = v_user
      and n.created_at > now() - interval '10 seconds'
  ) then
    raise exception 'rate_limit_short';
  end if;

  if (
    select count(*)
    from public.nvc_notes n
    where n.user_id = v_user
      and n.created_at > now() - interval '1 hour'
  ) >= 3 then
    raise exception 'rate_limit_hour';
  end if;

  if (
    select count(*)
    from public.nvc_notes n
    where n.user_id = v_user
      and n.created_at > now() - interval '24 hours'
  ) >= 10 then
    raise exception 'rate_limit_day';
  end if;

  if exists (
    select 1
    from public.nvc_notes n
    where n.user_id = v_user
      and n.record = v_record
      and lower(n.body) = lower(v_body)
      and n.created_at > now() - interval '7 days'
  ) then
    raise exception 'duplicate_note';
  end if;

  insert into public.nvc_notes (record, user_id, alias, body, status)
  values (v_record, v_user, v_alias, v_body, 'published')
  returning id into v_note_id;

  select count(*) into v_count
  from public.nvc_notes n
  where n.record = v_record
    and n.status = 'published';

  return query select v_note_id, v_count;
end;
$$;

revoke all on function public.nvc_get_interaction_counts(text[]) from public;
revoke all on function public.nvc_list_notes(text) from public;
revoke all on function public.nvc_toggle_resonance(text) from public;
revoke all on function public.nvc_add_note(text, text, text, text) from public;

grant execute on function public.nvc_get_interaction_counts(text[]) to anon, authenticated;
grant execute on function public.nvc_list_notes(text) to anon, authenticated;
revoke execute on function public.nvc_toggle_resonance(text) from anon;
revoke execute on function public.nvc_add_note(text, text, text, text) from anon;

grant execute on function public.nvc_toggle_resonance(text) to authenticated;
grant execute on function public.nvc_add_note(text, text, text, text) to authenticated;

commit;
